using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Autobahn.Stats;
using Autobahn.Ui.Contracts;

namespace Autobahn.Cli.Ui;

/// <summary>
/// Renders a finished run as one self-contained HTML file: the same application, a snapshot
/// from a file rather than a socket, and no server.
/// </summary>
/// <remarks>
/// Everything is inlined - scripts, styles and the icon font as data URIs - so the result can
/// be attached to a pull request or mailed to somebody without a web server, a network or a
/// second file. That costs size, and this is deliberately not the default report format: the
/// txt/csv/md/html renderings the run writes are small and this is not.
/// </remarks>
internal static partial class StaticExport
{
    /// <summary>
    /// Reads an artifact and writes the page beside it, or wherever it was asked to.
    /// </summary>
    /// <returns>The path written, or null with a reason on the console.</returns>
    public static string? Write(string artifactPath, string? outputPath)
    {
        if (!File.Exists(artifactPath))
        {
            Console.Error.WriteLine($"No such file: {artifactPath}");
            return null;
        }

        if (!RunArtifact.TryRead(File.ReadAllText(artifactPath), out var artifact))
        {
            Console.Error.WriteLine(
                $"{artifactPath} is not an Autobahn run artifact. That is the .json report a run writes.");
            return null;
        }

        if (!UiAssets.IsBuilt)
        {
            Console.Error.WriteLine(
                "This copy of Autobahn was built without its web interface, so there is nothing to export.");
            Console.Error.WriteLine("  dotnet tool update --global Transpose.Compiler");
            Console.Error.WriteLine("  ./scripts/build-ui.sh");
            return null;
        }

        var folder = Path.GetDirectoryName(Path.GetFullPath(artifactPath)) ?? ".";
        var snapshot = ArtifactSnapshot.Build(artifact, folder);

        var target = outputPath ?? Path.ChangeExtension(artifactPath, ".live.html");

        File.WriteAllText(target, Render(snapshot), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        return target;
    }

    /// <summary>
    /// The page: the shipped index.html with every reference to a file replaced by the file.
    /// </summary>
    /// <remarks>
    /// The shipped html is generated by the Transpose compiler and is the only place that knows
    /// which scripts the application needs and in what order, so it is rewritten rather than
    /// re-authored. A hand-written template here would be a second list of scripts to keep in
    /// step with the first.
    /// </remarks>
    private static string Render(RunSnapshot snapshot)
    {
        // Read before anything else runs: the application looks for this at start-up and skips
        // the socket entirely when it is there.
        var payload =
            "<script>window.__autobahnSnapshot = "
            + JsonSerializer.Serialize(snapshot, UiServer.JsonOptions)
            + ";</script>";

        // Into the template first, while it is still the small generated document. Inlining the
        // scripts before this point puts several megabytes of JavaScript in the way, and that
        // JavaScript contains the string "</head>" - a markup sanitizer builds documents out of
        // one - so the payload lands in the middle of a library instead of in the head.
        var html = UiAssets.ReadText("index.html")!.Replace("</head>", payload + "\n</head>");

        html = StylesheetLink().Replace(html, match => Stylesheet(match.Groups["href"].Value));

        return ScriptTag().Replace(html, match => Script(match.Groups["src"].Value));
    }

    private static string Stylesheet(string href)
    {
        var css = UiAssets.ReadText(href);
        if (css is null) return "";

        return "<style>" + InlineFonts(css, href) + "</style>";
    }

    private static string Script(string src)
    {
        var js = UiAssets.ReadText(src);

        return js is null ? "" : "<script>" + Escape(js) + "</script>";
    }

    /// <summary>
    /// Hides the three sequences that would end an inlined script early.
    /// </summary>
    /// <remarks>
    /// Not theoretical: this bundle carries a markdown parser and a syntax highlighter, so it
    /// has <c>&lt;!--</c> and <c>&lt;script</c> inside regular expressions. An html parser
    /// reading those inside a script element goes into its escaped and double-escaped states,
    /// after which the real <c>&lt;/script&gt;</c> does not close the element at all - and the
    /// rest of the page is swallowed as source code.
    ///
    /// Escaping only the <c>&lt;</c>, as <c>\x3C</c>, keeps every one of them the same string
    /// and the same regular expression to JavaScript.
    /// </remarks>
    private static string Escape(string js) =>
        DangerousSequence().Replace(js, match => "\\x3C" + match.Value[1..]);

    /// <summary>
    /// Replaces every font URL in a stylesheet with the font.
    /// </summary>
    /// <remarks>
    /// This is most of the file's size and there is no way around it: the icons are a font, and
    /// a self-contained page that cannot draw its icons is not one. Base64 costs a third on top
    /// of bytes that are already compressed.
    /// </remarks>
    private static string InlineFonts(string css, string stylesheetPath) =>
        FontUrl().Replace(css, match =>
        {
            var relative = match.Groups["url"].Value;
            var resolved = Resolve(stylesheetPath, relative);
            var bytes = UiAssets.ReadBytes(resolved);

            return bytes is null
                ? match.Value
                : $"url(data:font/woff2;base64,{Convert.ToBase64String(bytes)})";
        });

    /// <summary>A url inside a stylesheet is relative to the stylesheet, not to the page.</summary>
    private static string Resolve(string stylesheetPath, string relative)
    {
        var folder = Path.GetDirectoryName(stylesheetPath.Replace('\\', '/')) ?? "";

        var combined = folder.Length == 0 ? relative : folder + "/" + relative;
        var segments = new List<string>();

        foreach (var segment in combined.Split('/'))
        {
            if (segment == "." || segment.Length == 0) continue;
            if (segment == ".." && segments.Count > 0) segments.RemoveAt(segments.Count - 1);
            else if (segment != "..") segments.Add(segment);
        }

        return string.Join("/", segments);
    }

    [GeneratedRegex("""<link[^>]*rel=["']?stylesheet["']?[^>]*href=["'](?<href>[^"']+)["'][^>]*>""")]
    private static partial Regex StylesheetLink();

    [GeneratedRegex("""<script[^>]*src=["'](?<src>[^"']+)["'][^>]*>\s*</script>""")]
    private static partial Regex ScriptTag();

    [GeneratedRegex("<!--|</?script", RegexOptions.IgnoreCase)]
    private static partial Regex DangerousSequence();

    // The quotes are optional in css and the compiler emits them, so both forms are matched.
    [GeneratedRegex("""url\(\s*["']?(?<url>[^)"']+\.woff2[^)"']*)["']?\s*\)""")]
    private static partial Regex FontUrl();
}
