using System.Text;

namespace Autobahn.Http;

/// <summary>How the generated scenario is shaped and named.</summary>
public sealed record ScenarioCodeOptions
{
    /// <summary>What the generated scenario is called in the report.</summary>
    public string ScenarioName { get; init; } = "recorded";

    /// <summary>The namespace the generated class sits in. Empty emits a script instead.</summary>
    public string? Namespace { get; init; }

    /// <summary>The generated class's name, when a namespace was given.</summary>
    public string ClassName { get; init; } = "RecordedScenario";

    /// <summary>
    /// Pulled out as the client's base address, with the requests written relative to it.
    /// Null leaves every URL absolute.
    /// </summary>
    public string? BaseAddress { get; init; }

    /// <summary>The load plan written into the generated file, as source.</summary>
    public string LoadSimulations { get; init; } =
        "Simulation.Inject(rate: 10, interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromMinutes(1))";

    /// <summary>
    /// Whether each recorded request becomes its own named step.
    /// </summary>
    /// <remarks>
    /// On by default: a recorded session is a sequence of distinct calls, and one latency
    /// number spanning all of them says nothing about which one is slow.
    /// </remarks>
    public bool StepPerRequest { get; init; } = true;

    public static ScenarioCodeOptions Default { get; } = new();
}

/// <summary>
/// Writes the C# for a scenario that replays a recorded session.
/// </summary>
/// <remarks>
/// The output is source you own, not a recording the engine replays - which is the whole
/// point. A recording has one session's ids, one user's tokens and one moment's data baked
/// into it; those have to become feeds before the test means anything, and that is an edit to
/// a file rather than a configuration option on a black box. What the generator saves is the
/// transcription.
///
/// It marks what it could not decide for you, rather than guessing: every generated file
/// carries the same short list of what to replace.
/// </remarks>
public static class ScenarioCodeGenerator
{
    /// <summary>Turns a HAR recording straight into scenario source.</summary>
    public static string FromHar(string harJson, ScenarioCodeOptions? options = null, Har.HarFilter? filter = null) =>
        Generate(Har.Parse(harJson, filter), options);

    /// <summary>Turns already-converted requests into scenario source.</summary>
    public static string Generate(IReadOnlyList<HttpRequest> requests, ScenarioCodeOptions? options = null)
    {
        var config = options ?? ScenarioCodeOptions.Default;

        if (requests.Count == 0)
            throw new AutobahnException("There is nothing to generate from: the recording produced no requests.");

        var code = new StringBuilder();
        var isScript = string.IsNullOrWhiteSpace(config.Namespace);

        WriteHeader(code, config, requests.Count);

        var indent = isScript ? "" : "        ";

        if (!isScript)
        {
            code.AppendLine($"namespace {config.Namespace};");
            code.AppendLine();
            code.AppendLine($"public static class {config.ClassName}");
            code.AppendLine("{");
            code.AppendLine("    [ScenarioSource]");
            code.AppendLine("    public static ScenarioProps Build()");
            code.AppendLine("    {");
        }

        WriteClient(code, config, indent);
        WriteScenario(code, config, requests, indent);

        if (!isScript)
        {
            code.AppendLine("    }");
            code.AppendLine("}");
        }
        else
        {
            code.AppendLine();
            code.AppendLine("return scenario;");
        }

        return code.ToString();
    }

    private static void WriteHeader(StringBuilder code, ScenarioCodeOptions config, int requestCount)
    {
        var isScript = string.IsNullOrWhiteSpace(config.Namespace);

        code.AppendLine($"// Generated by Autobahn from a recorded session: {requestCount} request(s).");
        code.AppendLine("//");
        code.AppendLine("// This is a starting point, not a finished test. Before it measures anything useful:");
        code.AppendLine("//");
        code.AppendLine("//   1. Replace the hard-coded ids and payloads below with a Feed, or every virtual");
        code.AppendLine("//      user will ask for the same row and you will measure one cache entry.");
        code.AppendLine("//   2. Add the credentials the recording did not carry over - a recorded cookie or");
        code.AppendLine("//      bearer token belongs to one session and was deliberately dropped.");
        code.AppendLine("//   3. Decide what success means. A 2xx is the default; add .WithCheck(...) where an");
        code.AppendLine("//      endpoint can answer 200 and still have failed.");
        code.AppendLine("//   4. Set a load plan that reflects the traffic you are modelling.");
        code.AppendLine("//");

        if (isScript)
        {
            code.AppendLine("// Run it with: autobahn run <this file>");
            code.AppendLine();
        }
        else
        {
            code.AppendLine();
            code.AppendLine("using Autobahn;");
            code.AppendLine("using Autobahn.Http;");
            code.AppendLine();
        }
    }

    private static void WriteClient(StringBuilder code, ScenarioCodeOptions config, string indent)
    {
        code.AppendLine($"{indent}var client = HttpClientPool.CreateClient(new HttpClientSettings");
        code.AppendLine($"{indent}{{");

        if (config.BaseAddress is { Length: > 0 } baseAddress)
            code.AppendLine($"{indent}    BaseAddress = {Literal(baseAddress)},");

        code.AppendLine($"{indent}    Timeout = TimeSpan.FromSeconds(30)");
        code.AppendLine($"{indent}}});");
        code.AppendLine();
    }

    private static void WriteScenario(
        StringBuilder code, ScenarioCodeOptions config, IReadOnlyList<HttpRequest> requests, string indent)
    {
        code.AppendLine($"{indent}var scenario = Scenario.Create({Literal(config.ScenarioName)}, async context =>");
        code.AppendLine($"{indent}    {{");

        var body = indent + "        ";
        var names = StepNames(requests);

        for (var i = 0; i < requests.Count; i++)
        {
            var isLast = i == requests.Count - 1;
            WriteRequest(code, config, requests[i], names[i], body, isLast);
            if (!isLast) code.AppendLine();
        }

        code.AppendLine($"{indent}    }})");
        code.AppendLine($"{indent}    .WithoutWarmUp()");
        code.AppendLine($"{indent}    .WithLoadSimulations({config.LoadSimulations});");

        if (indent.Length > 0)
        {
            code.AppendLine();
            code.AppendLine($"{indent}return scenario;");
        }
    }

    private static void WriteRequest(
        StringBuilder code,
        ScenarioCodeOptions config,
        HttpRequest request,
        string stepName,
        string indent,
        bool isLast)
    {
        var url = RelativeUrl(request.Url, config.BaseAddress);
        var call = $"HttpRequest.{MethodName(request.Method)}({Literal(url)})";

        var lines = new List<string>();

        foreach (var (name, value) in request.Headers)
            lines.Add($".WithHeader({Literal(name)}, {Literal(value)})");

        if (request.CreateContent is not null)
        {
            using var content = request.CreateContent();
            var text = content.ReadAsStringAsync().GetAwaiter().GetResult();
            var contentType = content.Headers.ContentType?.MediaType ?? "application/json";

            // Written as a literal, and flagged: a recorded body is one moment's data, and
            // leaving it hard-coded is the difference between a load test and a replay.
            lines.Add($"// TODO: this body was recorded once - drive it from a Feed.");
            lines.Add($".WithStringBody({Literal(text)}, {Literal(contentType)})");
        }

        var built = lines.Count == 0
            ? call
            : call + Environment.NewLine + string.Join(Environment.NewLine, lines.Select(x => $"{indent}        {x}"));

        if (config.StepPerRequest)
        {
            var verb = isLast ? "return await" : "await";
            code.AppendLine($"{indent}{verb} Step.Run({Literal(stepName)}, context, () => client.Send(");
            code.AppendLine($"{indent}    {built.Replace(Environment.NewLine, Environment.NewLine)},");
            code.AppendLine($"{indent}    context));");
        }
        else
        {
            var verb = isLast ? "return await" : "await";
            code.AppendLine($"{indent}{verb} client.Send({built}, context);");
        }
    }

    /// <summary>
    /// A step name per request, from its path, made unique.
    /// </summary>
    /// <remarks>
    /// Names have to be unique or two different calls merge into one row in the report, which
    /// is exactly the confusion a per-request step was meant to avoid. A recorded session hits
    /// the same path more than once often enough that this is the common case, not the edge.
    /// </remarks>
    internal static string[] StepNames(IReadOnlyList<HttpRequest> requests)
    {
        var names = new string[requests.Count];
        var used = new Dictionary<string, int>(StringComparer.Ordinal);

        for (var i = 0; i < requests.Count; i++)
        {
            var name = StepName(requests[i]);

            if (used.TryGetValue(name, out var seen))
            {
                used[name] = seen + 1;
                name = $"{name}_{seen + 1}";
            }
            else
            {
                used[name] = 1;
            }

            names[i] = name;
        }

        return names;
    }

    private static string StepName(HttpRequest request)
    {
        var path = Uri.TryCreate(request.Url, UriKind.Absolute, out var uri)
            ? uri.AbsolutePath
            : request.Url.Split('?')[0];

        var segments = path.Split('/', StringSplitOptions.RemoveEmptyEntries);
        var tail = segments.Length == 0 ? "root" : string.Join("_", segments.TakeLast(2));

        var cleaned = new StringBuilder(tail.Length);

        foreach (var c in tail)
            cleaned.Append(char.IsLetterOrDigit(c) ? char.ToLowerInvariant(c) : '_');

        var name = cleaned.ToString().Trim('_');

        return $"{request.Method.Method.ToLowerInvariant()}_{(name.Length == 0 ? "root" : name)}";
    }

    private static string RelativeUrl(string url, string? baseAddress)
    {
        if (baseAddress is not { Length: > 0 }) return url;
        if (!url.StartsWith(baseAddress, StringComparison.OrdinalIgnoreCase)) return url;

        var relative = url[baseAddress.Length..];
        return relative.Length == 0 ? "/" : relative;
    }

    private static string MethodName(HttpMethod method) =>
        method.Method switch
        {
            "GET" => "Get",
            "POST" => "Post",
            "PUT" => "Put",
            "PATCH" => "Patch",
            "DELETE" => "Delete",
            "HEAD" => "Head",
            "OPTIONS" => "Options",
            _ => "Create"
        };

    /// <summary>
    /// A C# string literal for arbitrary recorded text.
    /// </summary>
    /// <remarks>
    /// Recorded bodies are full of quotes and backslashes, and a generator that emits
    /// something that will not compile has saved nobody anything. A verbatim literal handles
    /// everything except a quote, which doubles.
    /// </remarks>
    internal static string Literal(string value) =>
        value.Contains('\n') || value.Contains('\r') || value.Contains('\\') || value.Contains('"')
            ? $"@\"{value.Replace("\"", "\"\"")}\""
            : $"\"{value}\"";
}
