<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>Autobahn.Examples.MessageBrokers</RootNamespace>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Autobahn/Autobahn.csproj" />
        <ProjectReference Include="../../src/Autobahn.Mqtt/Autobahn.Mqtt.csproj" />
        <ProjectReference Include="../../src/Autobahn.Amqp/Autobahn.Amqp.csproj" />
    </ItemGroup>

</Project>
